#pragma once

#include "sampler.hpp"
#include "core/handle.hpp"  // #220 Step 1: cairns::Handle / ResourceManager
#include "rhi/resource_manager.hpp"
#include "rhi/resources.hpp"
#include "util/cpu_arena.hpp"  // #229 P3: BumpArena + ArenaSlice (interning)

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string_view>

#include <SDL3/SDL.h>

#include <fastgltf/glm_element_traits.hpp>
#include <fastgltf/core.hpp>
#include <fastgltf/tools.hpp>
#include <fastgltf/util.hpp>

// stb_image implementation symbols live in src/util/stb_impl.cpp (alongside
// stb_image_write's). Defining STB_IMAGE_IMPLEMENTATION here meant every TU
// that pulled gltf_loader.hpp (transitively, via engine.hpp) emitted them --
// fine when only main.cpp included engine.hpp, but breaks once the headless
// facade or other TUs do.
#include <stb_image.h>

#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/quaternion.hpp>
#include <glm/gtc/type_ptr.hpp>
#define GLM_ENABLE_EXPERIMENTAL
#include <glm/gtx/string_cast.hpp>
#include <glm/gtx/matrix_decompose.hpp>

#include "util/gpu_anim_types.hpp"

#include <memory>

namespace cairns {

// THESE FUNCTIONS WERE mostly GENERATED BY AI.
// "The year is 2026, I'm not writing gltf loading" -- Ivan Amies, Q1 2026
// The AI messed this up btw and cost me ~4 hours of debugging time. It would've been faster if I'd written it myself.

// #229 P3 string interning: a name is a byte slice into a persistent BumpArena
// (Engine::prefab_arena_). Pointer-free POD -- replaces the std::string members
// that embedded a heap pointer + escaped the block cap / hash.
using NameRef = cairns::ArenaSlice<char>;

// Fail loud on prefab-arena overflow: ArenaSlice::Alloc returns a null slice
// when the BumpArena is full, and the fill loop would then write through a
// nullptr. Abort with a clear "raise kPrefabArenaBytes" message instead.
template <typename T>
inline cairns::ArenaSlice<T> AllocSliceOrDie(cairns::BumpArena& arena,
                                             uint32_t n, const char* what) {
    cairns::ArenaSlice<T> s = cairns::ArenaSlice<T>::Alloc(arena, n);
    if (n > 0 && s.IsNull()) {
        std::fprintf(stderr,
                     "[PREFAB-ARENA] overflow: %u x %s -- raise kPrefabArenaBytes\n",
                     n, what);
        std::abort();
    }
    return s;
}

inline NameRef InternName(cairns::BumpArena& arena, std::string_view s) {
    NameRef r = AllocSliceOrDie<char>(arena, static_cast<uint32_t>(s.size()),
                                      "name byte");
    if (!r.IsNull()) {
        std::memcpy(r.data(arena), s.data(), s.size());
    }
    return r;
}

inline std::string_view ResolveName(cairns::BumpArena& arena, NameRef n) {
    return n.empty() ? std::string_view{}
                     : std::string_view(n.data(arena), n.count);
}

struct VertexAttribute {
    glm::vec4 color = glm::vec4(1.0f);
    glm::vec4 tangent = glm::vec4(0.0f);
    glm::vec4 normal = glm::vec4(0.0f, 0.0f, 1.0f, 0.0f);
    glm::vec2 uv = glm::vec2(0.0f);
    glm::vec2 pad1 = glm::vec2(0.0f);
};

struct AnimatedTRS {
    glm::vec3 T{0.0f};
    glm::quat R{1.0f, 0.0f, 0.0f, 0.0f};
    glm::vec3 S{1.0f};
};


// #221 Skinning Phase 1: per-vertex joint + weight payload for skinned
// meshes. 32 B; only populated for meshes whose primitives carry JOINTS_0
// / WEIGHTS_0. Unskinned meshes leave Mesh::Cold::cpuSkinAttrs empty so
// the static 3300-hero crowd pays 0 B/vert.
struct SkinVertex {
    glm::uvec4 joints = glm::uvec4(0);
    glm::vec4  weights = glm::vec4(1.0f, 0.0f, 0.0f, 0.0f);
};

// #222 Phase S.2: GPU-side packed skin vertex. 8 B (4x u8 joints + 4x u8
// unorm weights). Largest-remainder renorm during pack guarantees the
// weights sum to exactly 255 (post-quantization) so seams don't crack.
struct PackedSkinVertex {
    uint32_t joints_packed = 0;   // u8 j0 | u8 j1 | u8 j2 | u8 j3 (LSB first)
    uint32_t weights_packed = 0;  // u8 w0 | u8 w1 | u8 w2 | u8 w3
};

inline PackedSkinVertex PackSkinVertex(const SkinVertex& v) {
    PackedSkinVertex p;
    p.joints_packed =
        (v.joints.x & 0xFFu) |
        ((v.joints.y & 0xFFu) << 8) |
        ((v.joints.z & 0xFFu) << 16) |
        ((v.joints.w & 0xFFu) << 24);
    // u8 quantization with largest-remainder renorm. Compute floor(w*255)
    // per channel, distribute the deficit to the channels with the largest
    // fractional remainders.
    const float wsum =
        v.weights.x + v.weights.y + v.weights.z + v.weights.w;
    const float inv = (wsum > 1e-6f) ? (1.0f / wsum) : 0.0f;
    const float ns[4] = {
        v.weights.x * inv, v.weights.y * inv,
        v.weights.z * inv, v.weights.w * inv,
    };
    const float scaled[4] = {
        ns[0] * 255.0f, ns[1] * 255.0f, ns[2] * 255.0f, ns[3] * 255.0f,
    };
    uint32_t base[4] = {
        static_cast<uint32_t>(scaled[0]),
        static_cast<uint32_t>(scaled[1]),
        static_cast<uint32_t>(scaled[2]),
        static_cast<uint32_t>(scaled[3]),
    };
    uint32_t total = base[0] + base[1] + base[2] + base[3];
    int32_t deficit = 255 - static_cast<int32_t>(total);
    // give 1 LSB to the channels with the largest remainders, in order.
    for (int32_t k = 0; k < deficit && k < 4; ++k) {
        float best_rem = -1.0f;
        int best_idx = 0;
        for (int i = 0; i < 4; ++i) {
            const float rem = scaled[i] - static_cast<float>(base[i]);
            // skip channels we already bumped this round
            if (((base[i] + 1u) > 255u) || rem <= best_rem) {
                continue;
            }
            best_rem = rem;
            best_idx = i;
        }
        if (base[best_idx] < 255u) {
            base[best_idx]++;
        }
    }
    p.weights_packed =
        (base[0] & 0xFFu) |
        ((base[1] & 0xFFu) << 8) |
        ((base[2] & 0xFFu) << 16) |
        ((base[3] & 0xFFu) << 24);
    return p;
}

struct Primitive {
    uint32_t firstIndex = 0;
    uint32_t indexCount = 0;
    int32_t  vertexOffset = 0; // Base Vertex (added to index value)
    uint32_t materialIndex = 0;
};

// #220 Step 2: Aaltonen Hot/Cold split. Pooled via
// cairns::ResourceManager<Mesh> on Engine; MeshId is Handle<Mesh>.
// Scene::meshes is now std::vector<MeshId> -- mesh data is engine-owned,
// not nested in Scene, so multiple scenes can later reference the same
// loaded GLB through AssetRegistry. Primitive stays a std::vector inside
// Hot for now (Tier-3 flat array, recorder iterates per draw); becomes
// a Span<Primitive> candidate in the allocator sweep round, separate axis.
struct Mesh {
    struct Hot {
        // Read on every draw of this mesh.
        rhi::Handle<rhi::Buffer> posHandle;
        rhi::Handle<rhi::Buffer> attrHandle; // shared vertex-stream attrs
        rhi::Handle<rhi::Buffer> indexHandle;
        std::vector<Primitive> primitives;
        // #221 Skinning F5: snapshot of LoadPrefabsGpu's running_vert at the
        // patch site. Skinned draws subtract this to get the mesh-local
        // baseVertex (vkCmdDrawIndexed has ONE vertexOffset, which today
        // serves stream 0 + stream 1 globally; the skinned stream-0 binds
        // a per-actor slice of skin_output_pool_ that's mesh-local indexed).
        uint32_t global_base_vertex = 0;
        // #221 Skinning Phase 1: base index into the shared skin-attr SSBO
        // for this mesh's slice (0 for unskinned meshes, which contribute
        // nothing to the shared skin buffer).
        uint32_t skin_attr_base_vertex = 0;
        // #221 Skinning Phase 9: snapshot of cpuPositions.size() taken at
        // upload, before CleanupTmps clears the CPU temporaries. Skinning
        // path reads this to size the kernel dispatch + the
        // skin_output_pool_ slice (cpuPositions itself is gone by then).
        uint32_t vert_count = 0;
        // #222 Phase S.3: bind-pose AABB in mesh-local space. Computed at
        // load over cpuPositions; persists past CleanupTmps. Per-actor
        // frustum cull transforms this by the actor's world xform, pads
        // by 1.5x for animation motion, and tests against the camera's
        // 6 planes (skip the actor's anim_eval + skin dispatch when
        // fully outside).
        glm::vec3 bind_aabb_min = glm::vec3(0.0f);
        glm::vec3 bind_aabb_max = glm::vec3(0.0f);
        // #221 Skinning F5: per-skinned-mesh alias of the shared attr region
        // pre-offset by global_base_vertex * sizeof(VertexAttribute). Stream
        // 1 binds this for skinned draws; mesh-local vertex_offset then
        // indexes correctly. Null for unskinned meshes (they use attrHandle).
        rhi::Handle<rhi::Buffer> attr_skinned_alias;
        // #222 Phase H.4: skin_attrs_buffer retired from Mesh::Hot
        // (same handle on every skinned mesh from one LoadPrefabsGpu).
        // Now returned via LoadPrefabsGpu's out_shared_skin and stashed on
        // Engine::per_batch_shared_skin_; recorder resolves via batch_id.
        // #221 Skinning Phase 9 (vk): Group A descriptor set for this
        // skinned mesh (positions slice + skin-attrs slice). Allocated at
        // scene load via Resources::CreateSkinGroupA. Null on Metal (Metal's
        // compute path binds buffers directly per batch).
        rhi::Handle<rhi::BindGroup> skin_group_a;
        // #224 L1: index into Engine::per_batch_shared_skin_ identifying
        // which LoadPrefabBatch upload produced this mesh's shared skin
        // attrs buffer. 0 for unskinned meshes (never read) and for the
        // single boot-time batch. Group A binding 1 reads the buffer via
        // engine.per_batch_shared_skin_[batch_id]; the H.4 dedup is now
        // *within* a batch, not across the program.
        uint16_t batch_id = 0;
    };
    struct Cold {
        NameRef name;  // #229 P3: slice into prefab_arena_ (was std::string)
        // CPU load-time temporaries. Cleared post-upload by Engine's mesh-pool
        // sweep. #229: these stay on malloc, NOT cpu_block_. Measured ~600 MB
        // across the 100-GLB batch (~6.5M verts x ~92 B), peaking before the
        // per-batch clear -- too big for even a 512 MB block. They are transient
        // (empty before any frame, not in the determinism hash). Proper in-block
        // home = a kRegionLoadScratch arena freed PER MESH (peak = 1 mesh, not
        // the whole batch); until then, malloc.
        std::vector<glm::vec4> cpuPositions;
        std::vector<VertexAttribute> cpuAttrs;
        std::vector<uint32_t> cpuIndices;
        // #221 Skinning Phase 1: per-vertex joint indices + weights aligned
        // with cpuPositions/cpuAttrs (size() == cpuPositions.size() when
        // mesh is skinned; empty when not).
        std::vector<SkinVertex> cpuSkinAttrs;
    };
};

struct Node {
    // #229 P3: pointer-free POD. name/children are slices into Engine::
    // prefab_arena_ (resolve via the threaded BumpArena), not heap std::string/
    // std::vector -- so Node is raw-hashable + lives under the block cap.
    NameRef name;
    glm::mat4 localTransform = glm::mat4(1.0f);
    glm::mat4 globalTransform = glm::mat4(1.0f);

    int32_t meshIndex = -1; // Index into Scene.meshes
    // #221 Skinning Phase 1: per-glTF node skin reference. -1 = no skin.
    int32_t skinIndex = -1; // Index into Prefab::Cold::skins.
    cairns::ArenaSlice<int32_t> children;
};

// #221 Skinning Phase 1: per-glTF skin (joint set + inverse binds). Joints
// reference Prefab::Cold::nodes by index; inverseBinds is one mat4 per joint
// in the same order. skeletonRoot is the glTF "skeleton" hint (-1 if absent;
// not used by the runtime — joint world matrices come from the node walk).
struct Skin {
    // #229 P3: slices into Engine::prefab_arena_ (was heap std::vector).
    cairns::ArenaSlice<int32_t> jointNodes;
    cairns::ArenaSlice<glm::mat4> inverseBinds;
    int32_t skeletonRoot = -1;
};

// #221 Skinning Phase 1: animation primitives. AnimationSampler stores the
// keyframe array for one channel (times + values + interpolation mode).
// Channel binds a sampler to a (node, path) target. Clip groups them under
// one name + duration.
enum class AnimationInterpolation : uint8_t {
    kStep,
    kLinear,
    kCubicSpline,
};

enum class AnimationPath : uint8_t {
    kTranslation,
    kRotation,
    kScale,
    kWeights,
};

struct AnimationSampler {
    // #229 M1: keyframes are NOT read at parse. Parse stores the glTF accessor
    // handles + the output's value shape; only the SELECTED walk clip's
    // samplers are read (into the flat gpu_times/gpu_values) at flatten time,
    // so the dozens of unused clips cost zero keyframe allocations. value_kind:
    // 0=Vec3 (T/S, widen w=0), 1=Vec4 (R quat), 2=Scalar (weights, .x).
    uint32_t input_accessor = 0;
    uint32_t output_accessor = 0;
    uint8_t value_kind = 0;
    AnimationInterpolation interp = AnimationInterpolation::kLinear;
};

struct AnimationChannel {
    int32_t samplerIndex = -1;
    int32_t nodeIndex = -1;
    AnimationPath path = AnimationPath::kTranslation;
};

struct Clip {
    // #229 P3: name + sampler/channel arrays are slices into prefab_arena_.
    NameRef name;
    cairns::ArenaSlice<AnimationSampler> samplers;
    cairns::ArenaSlice<AnimationChannel> channels;
    float duration = 0.0f;
};

struct LoadedTexture {
    int64_t width = 0;
    int64_t height = 0;
    int64_t levels = 1;
    int64_t src_bytes_per_row = 0;
    unsigned char* src_image = nullptr;
};

struct LoadedSampler {
    rhi::SamplerFilter minFilter = rhi::SamplerFilter::Linear;
    rhi::SamplerFilter magFilter = rhi::SamplerFilter::Linear;
    rhi::SamplerMipFilter mipFilter = rhi::SamplerMipFilter::None;
    rhi::SamplerAddressMode addressModeU = rhi::SamplerAddressMode::Repeat;
    rhi::SamplerAddressMode addressModeV = rhi::SamplerAddressMode::Repeat;
};

// #220 Step 1: Aaltonen Hot/Cold split. Hot is what the recorder reads
// every draw (the set-2 bind group only); Cold is the material's
// constituent texture + sampler, read at bind-group-build time. Pooled
// via cairns::ResourceManager<Material> on Engine; MatId is now
// Handle<Material> instead of a bare uint32_t index.
struct Material {
    struct Hot {
        rhi::Handle<rhi::BindGroup> set2;
    };
    struct Cold {
        rhi::Handle<rhi::Texture> color;
        rhi::Handle<rhi::Sampler> sampler;
    };
};

// #220 Step 3: Aaltonen Hot/Cold split. Pooled via
// cairns::ResourceManager<Prefab> on Engine; PrefabId = Handle<Prefab>.
// Hot is what extract reads at draw-build (mesh ids, mat ids, root
// nodes, per-scene texture/sampler registry); Cold is the node tree
// (walked once per frame in BuildMeshOpaqueDraws but not per draw)
// and the load-time temporaries cleared after upload.
struct Prefab {
    struct Hot {
        // #220 Step 2: was std::vector<Mesh>. Mesh data is engine-owned
        // via cairns::ResourceManager<Mesh>; Scene only holds the handles.
        // #229 P3: nested pool vectors re-seated onto cpu_block_ in
        // LoadPrefabFromGltf (block-backed = under the 1 GB cap + hash-reachable).
        std::vector<cairns::Handle<Mesh>, cairns::ChunkStdAllocator<cairns::Handle<Mesh>>> meshes;
        std::vector<int32_t, cairns::ChunkStdAllocator<int32_t>> rootNodes;
        // Renamed from materialIds (legacy uint32_t name). Each element
        // is a Handle<Material> into Engine::materials_.
        std::vector<cairns::Handle<Material>, cairns::ChunkStdAllocator<cairns::Handle<Material>>> materials;

        // #221 Phase 5b: index into engine's flat scene_headers array.
        // UINT32_MAX = scene not registered with anim_eval (no skin/clip).
        uint32_t gpu_prefab_header_idx = UINT32_MAX;
    };
    struct Cold {
        // #229 P3: outer arrays re-seated onto cpu_block_ in LoadPrefabFromGltf.
        // nodes/skins/clips element types still carry their own nested heap
        // members (Node::children/name, Skin/Clip vectors, names) -- those inner
        // vectors stay on malloc as a documented follow-on (string interning).
        std::vector<Node, cairns::ChunkStdAllocator<Node>> nodes;
        std::vector<AnimatedTRS, cairns::ChunkStdAllocator<AnimatedTRS>> bind_pose;
        // #222 Phase H.6 finish: per-scene texture/sampler registry. Only
        // read at material setup (PreparePrefabResources) + resident_textures
        // population (Engine::resident_textures_ built once post-upload).
        // Demoted from Hot since no per-frame reader exists.
        std::vector<rhi::Handle<rhi::Texture>, cairns::ChunkStdAllocator<rhi::Handle<rhi::Texture>>> textureHandles;
        std::vector<rhi::Handle<rhi::Sampler>, cairns::ChunkStdAllocator<rhi::Handle<rhi::Sampler>>> samplerHandles;
        // #221 Phase 5b: per-scene flat tables for GPU palette eval.
        // Populated at load by LoadPrefabFromGltf and consumed by
        // engine's anim-table upload sweep.
        std::vector<int32_t, cairns::ChunkStdAllocator<int32_t>> gpu_parent;
        std::vector<int32_t, cairns::ChunkStdAllocator<int32_t>> gpu_topo;
        std::vector<GpuTRS, cairns::ChunkStdAllocator<GpuTRS>> gpu_bind_pose;
        std::vector<GpuChannel, cairns::ChunkStdAllocator<GpuChannel>> gpu_channels;
        std::vector<GpuSampler, cairns::ChunkStdAllocator<GpuSampler>> gpu_samplers;
        std::vector<float, cairns::ChunkStdAllocator<float>> gpu_times;
        std::vector<glm::vec4, cairns::ChunkStdAllocator<glm::vec4>> gpu_values;
        std::vector<int32_t, cairns::ChunkStdAllocator<int32_t>> gpu_joint_nodes;
        std::vector<glm::mat4, cairns::ChunkStdAllocator<glm::mat4>> gpu_inverse_binds;
        int32_t gpu_mesh_node = -1;
        float gpu_clip_duration = 0.0f;
        // #221 Skinning Phase 1: glTF skins + clips for this scene. Per
        // decision 2 of plan v7 these ride std::vector on Cold to match
        // the existing shape (proper Tier-1 bump migration is a separate
        // sweep). Clips are kept long-lived (not in CleanupTmps) since
        // animation playback needs them past load.
        std::vector<Skin, cairns::ChunkStdAllocator<Skin>> skins;
        std::vector<Clip, cairns::ChunkStdAllocator<Clip>> clips;
        // Load-time temporaries cleared post-upload via CleanupTmps.
        std::vector<LoadedSampler, cairns::ChunkStdAllocator<LoadedSampler>> loaded_samplers;
        std::vector<LoadedTexture, cairns::ChunkStdAllocator<LoadedTexture>> loaded_textures;
        std::vector<uint32_t, cairns::ChunkStdAllocator<uint32_t>> materialToTextureIndex;
        std::vector<uint32_t, cairns::ChunkStdAllocator<uint32_t>> materialToSamplerIndex;

        void CleanupTmps() {
            for ( size_t i = 0; i < loaded_textures.size(); ++i ) {
                auto& tex_desc = loaded_textures[i];
                stbi_image_free(tex_desc.src_image);
            }
            loaded_textures.clear();
            loaded_samplers.clear();
            materialToTextureIndex.clear();
            materialToSamplerIndex.clear();
        }
    };
};
using PrefabId = cairns::Handle<Prefab>;

// #220 Step 2: writes split-out Hot + Cold sides instead of a combined
// Mesh value. Caller (LoadPrefabFromGltf) is responsible for Acquiring
// the pool slot and handing in fresh refs to its Hot/Cold cells.
inline bool LoadMeshFromGltf(const fastgltf::Asset& asset,
                             const fastgltf::Mesh& gltfMesh,
                             Mesh::Hot& outHot, Mesh::Cold& outCold,
                             [[maybe_unused]] cairns::ChunkAllocator& block,
                             cairns::BumpArena& arena) {
    outCold.name = InternName(arena, std::string_view(gltfMesh.name.data(),
                                                       gltfMesh.name.size()));
    // #229: cpu* stay on malloc (transient ~600 MB load buffers; see Mesh::Cold).
    // Clear them -- reused per mesh, dropped post-upload.
    outCold.cpuPositions.clear();
    outCold.cpuAttrs.clear();
    outCold.cpuIndices.clear();
    outCold.cpuSkinAttrs.clear();

    // #221 Skinning Phase 1: mesh is "skinned" if ANY primitive carries
    // JOINTS_0 (per glTF spec, JOINTS_0 + WEIGHTS_0 travel together).
    // Skinned meshes get cpuSkinAttrs aligned with cpuPositions, padded
    // with identity-weight rows for any primitive that lacks the attribute.
    // Unskinned meshes leave cpuSkinAttrs empty so the static crowd pays 0 B/vert.
    // #229 M3: one pre-pass for skinned-ness + total vertex/index counts, so
    // the cpu* arrays are sized once instead of growing through the
    // ~14-realloc doubling chain per mesh.
    bool mesh_skinned = false;
    size_t total_verts = 0;
    size_t total_indices = 0;
    for (const auto& primitive : gltfMesh.primitives) {
        if (primitive.findAttribute("JOINTS_0") != primitive.attributes.end()) {
            mesh_skinned = true;
        }
        const auto* posIt = primitive.findAttribute("POSITION");
        if (posIt != primitive.attributes.end()) {
            total_verts += asset.accessors[posIt->accessorIndex].count;
        }
        if (primitive.indicesAccessor.has_value()) {
            total_indices += asset.accessors[*primitive.indicesAccessor].count;
        }
    }
    outCold.cpuPositions.reserve(total_verts);
    outCold.cpuAttrs.reserve(total_verts);
    outCold.cpuIndices.reserve(total_indices);
    if (mesh_skinned) {
        outCold.cpuSkinAttrs.reserve(total_verts);
    }

    // #222 Phase S.3: accumulate bind-pose AABB across all primitives.
    glm::vec3 aabb_min(std::numeric_limits<float>::max());
    glm::vec3 aabb_max(std::numeric_limits<float>::lowest());
    for (const auto& primitive : gltfMesh.primitives) {
        Primitive outPrim;
        outPrim.materialIndex = static_cast<uint32_t>(primitive.materialIndex.value_or(0));

        // Offset management: Where this primitive starts in the "Big Buffer"
        outPrim.vertexOffset = static_cast<int32_t>(outCold.cpuPositions.size());
        outPrim.firstIndex = static_cast<uint32_t>(outCold.cpuIndices.size());

        size_t vertexCount = 0;

        // 1. POSITIONS
        const auto* posIt = primitive.findAttribute("POSITION");
        if (posIt != primitive.attributes.end()) {
            auto& accessor = asset.accessors[posIt->accessorIndex];
            vertexCount = accessor.count;
            fastgltf::iterateAccessorWithIndex<glm::vec3>(asset, accessor, [&](glm::vec3 v, [[maybe_unused]] size_t i) {
                outCold.cpuPositions.push_back(glm::vec4(v, 1.0f));
                aabb_min = glm::min(aabb_min, v);
                aabb_max = glm::max(aabb_max, v);
            });
        }

        // Resize attributes
        size_t currentAttrOffset = outCold.cpuAttrs.size();
        outCold.cpuAttrs.resize(currentAttrOffset + vertexCount);

        // 2. NORMALS
        const auto* normIt = primitive.findAttribute("NORMAL");
        if (normIt != primitive.attributes.end()) {
            auto& accessor = asset.accessors[normIt->accessorIndex];
            fastgltf::iterateAccessorWithIndex<glm::vec3>(asset, accessor, [&](glm::vec3 v, size_t i) {
                outCold.cpuAttrs[currentAttrOffset + i].normal = glm::vec4(v, 0.0f);
            });
        }

        // 3. UVs
        const auto* uvIt = primitive.findAttribute("TEXCOORD_0");
        if (uvIt != primitive.attributes.end()) {
            auto& accessor = asset.accessors[uvIt->accessorIndex];
            fastgltf::iterateAccessorWithIndex<glm::vec2>(asset, accessor, [&](glm::vec2 v, size_t i) {
                outCold.cpuAttrs[currentAttrOffset + i].uv = glm::vec2(v.x, v.y);
            });
        }

        // 4. COLOR
        const auto* colIt = primitive.findAttribute("COLOR_0");
        if (colIt != primitive.attributes.end()) {
            auto& accessor = asset.accessors[colIt->accessorIndex];
            fastgltf::iterateAccessorWithIndex<glm::vec4>(asset, accessor, [&](glm::vec4 v, size_t i) {
                outCold.cpuAttrs[currentAttrOffset + i].color = v;
            });
        }

        // #221 Skinning Phase 1: JOINTS_0 + WEIGHTS_0. Only allocate the
        // skin-attr slice when the mesh is skinned (mesh_skinned was set
        // by the pre-pass). When this specific primitive lacks the
        // attribute but a sibling has it, fall back to identity-weight
        // bound to joint 0 -- still produces correct deformation because
        // the joint 0 palette matrix is whatever its skin says it is, and
        // weight=(1,0,0,0) collapses the blend to that single matrix.
        if (mesh_skinned) {
            size_t currentSkinOffset = outCold.cpuSkinAttrs.size();
            outCold.cpuSkinAttrs.resize(currentSkinOffset + vertexCount);
            const auto* jointsIt = primitive.findAttribute("JOINTS_0");
            const auto* weightsIt = primitive.findAttribute("WEIGHTS_0");
            if (jointsIt != primitive.attributes.end()) {
                auto& accessor = asset.accessors[jointsIt->accessorIndex];
                // glTF JOINTS_0 is u8 or u16; fastgltf widens via the
                // u32vec4 iterator template.
                fastgltf::iterateAccessorWithIndex<glm::u32vec4>(asset, accessor, [&](glm::u32vec4 v, size_t i) {
                    outCold.cpuSkinAttrs[currentSkinOffset + i].joints = v;
                });
            }
            if (weightsIt != primitive.attributes.end()) {
                auto& accessor = asset.accessors[weightsIt->accessorIndex];
                fastgltf::iterateAccessorWithIndex<glm::vec4>(asset, accessor, [&](glm::vec4 v, size_t i) {
                    outCold.cpuSkinAttrs[currentSkinOffset + i].weights = v;
                });
            }
            // SkinVertex default ctor leaves identity weights (1,0,0,0) +
            // joints (0,0,0,0) for any element neither JOINTS_0 nor
            // WEIGHTS_0 wrote.
        }

        // 5. INDICES
        if (primitive.indicesAccessor.has_value()) {
            auto& accessor = asset.accessors[*primitive.indicesAccessor];
            outPrim.indexCount = static_cast<uint32_t>(accessor.count);
            fastgltf::iterateAccessorWithIndex<uint32_t>(asset, accessor, [&](uint32_t idx, [[maybe_unused]] size_t i) {
                // Keep indices 0-based relative to the primitive slice
                // Draw command will add `vertexOffset` (baseVertex) to these
                outCold.cpuIndices.push_back(idx);
            });
        }

        outHot.primitives.push_back(outPrim);
    }
    // #222 Phase S.3: bake AABB on Hot. Empty meshes (no POSITION accessor)
    // leave the AABB at the sentinel; consumers must gate on the inverted
    // case (min > max) and treat them as "always visible" to avoid culling
    // by accident.
    if (aabb_min.x <= aabb_max.x) {
        outHot.bind_aabb_min = aabb_min;
        outHot.bind_aabb_max = aabb_max;
    }
    return true;
}

// #220 Step 3: writes split-out Scene Hot + Cold sides; meshes still
// land in the engine's Mesh pool via the threaded reference.
inline bool LoadPrefabFromGltf(const std::filesystem::path& path,
                               Prefab::Hot& hot, Prefab::Cold& cold,
                               cairns::ResourceManager<Mesh>& meshes_pool,
                               cairns::ChunkAllocator& block,
                               cairns::BumpArena& arena) {
    // #229 P3: re-seat the prefab's nested pool vectors onto cpu_block_ before
    // any fill (POCMA move-assign adopts the block; vectors are empty fresh from
    // Acquire). Node/Skin/Clip element inner heap stays on malloc (follow-on).
    auto reseat = [&block](auto& v) {
        using V = std::decay_t<decltype(v)>;
        v = V(typename V::allocator_type(block));
    };
    reseat(hot.meshes);
    reseat(hot.rootNodes);
    reseat(hot.materials);
    reseat(cold.nodes);
    reseat(cold.bind_pose);
    reseat(cold.textureHandles);
    reseat(cold.samplerHandles);
    reseat(cold.gpu_parent);
    reseat(cold.gpu_topo);
    reseat(cold.gpu_bind_pose);
    reseat(cold.gpu_channels);
    reseat(cold.gpu_samplers);
    reseat(cold.gpu_times);
    reseat(cold.gpu_values);
    reseat(cold.gpu_joint_nodes);
    reseat(cold.gpu_inverse_binds);
    reseat(cold.skins);
    reseat(cold.clips);
    reseat(cold.loaded_samplers);
    reseat(cold.loaded_textures);
    reseat(cold.materialToTextureIndex);
    reseat(cold.materialToSamplerIndex);

    size_t byte_count = 0;
    void* file_data = SDL_LoadFile(path.string().c_str(), &byte_count);
    if (!file_data) return false;
    fastgltf::Parser parser;
    auto data = fastgltf::GltfDataBuffer::FromBytes(
        static_cast<const std::byte*>(file_data), byte_count);
    SDL_free(file_data);
    if (data.error() != fastgltf::Error::None) return false;
    auto assetRes = parser.loadGltfBinary(data.get(), path.parent_path(), fastgltf::Options::None);
    if (assetRes.error() != fastgltf::Error::None) return false;
    const auto& asset = assetRes.get();

    // 1. Textures
    for (const auto& image : asset.images) {
        LoadedTexture texDesc;
        const uint8_t* bytes = nullptr; size_t byteLength = 0;
        
        const auto* bufferView = std::get_if<fastgltf::sources::BufferView>(&image.data);
        const auto* byteView = std::get_if<fastgltf::sources::ByteView>(&image.data);
        if (bufferView) {
            auto& view = asset.bufferViews[bufferView->bufferViewIndex];
            auto& buffer = asset.buffers[view.bufferIndex];
            if (auto* vb = std::get_if<fastgltf::sources::Vector>(&buffer.data)) {
                bytes = reinterpret_cast<const uint8_t*>(vb->bytes.data()) + view.byteOffset;
                byteLength = view.byteLength;
            }
            else if (auto* ab = std::get_if<fastgltf::sources::Array>(&buffer.data)) {
                bytes = reinterpret_cast<const uint8_t*>(ab->bytes.data()) + view.byteOffset;
                byteLength = view.byteLength;
            }
        } else if (byteView) {
            bytes = reinterpret_cast<const uint8_t*>(byteView->bytes.data());
            byteLength = byteView->bytes.size();
        }

        if (bytes) {
            int w, h, c;
            unsigned char* raw = stbi_load_from_memory(bytes, (int)byteLength, &w, &h, &c, 4);
            if (raw) {
                texDesc.width = w;
                texDesc.height = h;
                // todo @iamies don't assume all loaded textures must be mip-mapped
                texDesc.levels = static_cast<uint32_t>(std::floor(std::log2(std::max(w, h)))) + 1;
                texDesc.src_bytes_per_row = 4 * w;
                texDesc.src_image = raw;
                cold.loaded_textures.push_back(texDesc);
            }
        }
    }
    
    // 2. Samplers
    // todo @iamies implement mip-mapped samplers
    for (const auto& s : asset.samplers) {
        LoadedSampler info;
        // todo @iamies remove this mipmap injection hack
        if (s.minFilter || !s.minFilter) {
            fastgltf::Filter f;
            if ( s.minFilter ) {
                f = *s.minFilter;
            }
            else {
                f = fastgltf::Filter::NearestMipMapLinear;
            }
            // Check for Nearest variants
            if (f == fastgltf::Filter::Nearest ||
                f == fastgltf::Filter::NearestMipMapNearest ||
                f == fastgltf::Filter::NearestMipMapLinear) {
                info.minFilter = rhi::SamplerFilter::Nearest;
            } else {
                info.minFilter = rhi::SamplerFilter::Linear;
            }

            // Check for Mipmap variants
            if (f == fastgltf::Filter::NearestMipMapNearest || f == fastgltf::Filter::LinearMipMapNearest) {
                info.mipFilter = rhi::SamplerMipFilter::Nearest;
            } else if (f == fastgltf::Filter::NearestMipMapLinear || f == fastgltf::Filter::LinearMipMapLinear) {
                info.mipFilter = rhi::SamplerMipFilter::Linear;
            } else {
                info.mipFilter = rhi::SamplerMipFilter::None;
            }
        }
        if (s.magFilter) {
            info.magFilter = (*s.magFilter == fastgltf::Filter::Nearest) ?
            rhi::SamplerFilter::Nearest : rhi::SamplerFilter::Linear;
        }
        auto mapWrap = [](fastgltf::Wrap w) {
            if(w==fastgltf::Wrap::ClampToEdge) return rhi::SamplerAddressMode::ClampToEdge;
            if(w==fastgltf::Wrap::MirroredRepeat) return rhi::SamplerAddressMode::MirroredRepeat;
            return rhi::SamplerAddressMode::Repeat;
        };
        info.addressModeU = mapWrap(s.wrapS); info.addressModeV = mapWrap(s.wrapT);
        cold.loaded_samplers.push_back(info);
    }
    
    // 3. Material Mapping
    // ONLY DOES UNLIT MATERIALS
    for (size_t i = 0; i < asset.materials.size(); ++i) {
        const auto& mat = asset.materials[i];
        if (mat.pbrData.baseColorTexture.has_value()) {
            size_t texIdx = mat.pbrData.baseColorTexture->textureIndex;
            int32_t image_index = -1;
            if (texIdx < asset.textures.size() && asset.textures[texIdx].imageIndex.has_value()) {
                image_index = static_cast<uint32_t>(*asset.textures[texIdx].imageIndex);
            }
            int32_t sampler_index = -1;
            if ( texIdx < asset.textures.size() && asset.textures[texIdx].samplerIndex.has_value()) {
                sampler_index = static_cast<uint32_t>(*asset.textures[texIdx].samplerIndex);
            }
            if ( image_index >= 0 && sampler_index >= 0 ) {
                cold.materialToTextureIndex.push_back(image_index);
                cold.materialToSamplerIndex.push_back(sampler_index);
            }
        }
    }

    // 4. Meshes -- #220 Step 2: acquire pool slot per gltf mesh, write
    // Hot+Cold, push the MeshId into the Scene's mesh list.
    for (size_t i = 0; i < asset.meshes.size(); ++i) {
        cairns::Handle<Mesh> mid = meshes_pool.Acquire();
        Mesh::Hot* mhot = meshes_pool.GetHot(mid);
        Mesh::Cold* mcold = meshes_pool.GetCold(mid);
        LoadMeshFromGltf(asset, asset.meshes[i], *mhot, *mcold, block, arena);
        hot.meshes.push_back(mid);
    }
    
    // 5. Nodes
    for (size_t i = 0; i < asset.nodes.size(); ++i) {
        cold.nodes.push_back(Node());
        auto& gn = asset.nodes[i];
        auto& on = cold.nodes[i];
        on.name = InternName(arena,
                             std::string_view(gn.name.data(), gn.name.size()));
        if (const auto* trs = std::get_if<fastgltf::TRS>(&gn.transform)) {
            glm::vec3 t(trs->translation[0], trs->translation[1], trs->translation[2]);
            glm::quat r(trs->rotation[3], trs->rotation[0], trs->rotation[1], trs->rotation[2]);
            glm::vec3 s(trs->scale[0], trs->scale[1], trs->scale[2]);
            on.localTransform = glm::translate(glm::mat4(1.0f), t) * glm::mat4(r) * glm::scale(glm::mat4(1.0f), s);
        } else if (const auto* mat = std::get_if<fastgltf::math::fmat4x4>(&gn.transform)) {
            on.localTransform = glm::make_mat4(mat->data());
        }
        if (gn.meshIndex.has_value()) on.meshIndex = static_cast<int32_t>(*gn.meshIndex);
        // #221 Skinning Phase 1: glTF skin reference.
        if (gn.skinIndex.has_value()) {
            on.skinIndex = static_cast<int32_t>(*gn.skinIndex);
        }
        on.children = AllocSliceOrDie<int32_t>(
            arena, static_cast<uint32_t>(gn.children.size()), "node child");
        for (size_t ci = 0; ci < gn.children.size(); ++ci) {
            on.children.data(arena)[ci] = static_cast<int32_t>(gn.children[ci]);
        }
    }

    // #221 Skinning Phase 1: skins. Inverse binds are optional in glTF;
    // when absent the spec says treat as identity (each joint contributes
    // raw world-space transform pre-multiplied by the mesh's inverse bind).
    for (size_t si = 0; si < asset.skins.size(); ++si) {
        const auto& gskin = asset.skins[si];
        Skin out;
        out.skeletonRoot = gskin.skeleton.has_value()
                               ? static_cast<int32_t>(*gskin.skeleton)
                               : -1;
        const uint32_t joint_count = static_cast<uint32_t>(gskin.joints.size());
        out.jointNodes =
            AllocSliceOrDie<int32_t>(arena, joint_count, "skin joint");
        for (uint32_t j = 0; j < joint_count; ++j) {
            out.jointNodes.data(arena)[j] = static_cast<int32_t>(gskin.joints[j]);
        }
        out.inverseBinds =
            AllocSliceOrDie<glm::mat4>(arena, joint_count, "skin inverse-bind");
        for (uint32_t j = 0; j < joint_count; ++j) {
            out.inverseBinds.data(arena)[j] = glm::mat4(1.0f);
        }
        if (gskin.inverseBindMatrices.has_value()) {
            auto& accessor = asset.accessors[*gskin.inverseBindMatrices];
            fastgltf::iterateAccessorWithIndex<fastgltf::math::fmat4x4>(
                asset, accessor,
                [&](const fastgltf::math::fmat4x4& m, size_t i) {
                    if (i < out.inverseBinds.size()) {
                        out.inverseBinds.data(arena)[i] = glm::make_mat4(m.data());
                    }
                });
        }
        cold.skins.push_back(std::move(out));
    }

    // #221 Skinning Phase 1: animations. One Clip per glTF animation; samplers
    // packed as {times[], values[]} with values widened to vec4 so quat
    // (rotation) and vec3 (T/S) share a single readers-branch-on-path layout.
    for (size_t ci = 0; ci < asset.animations.size(); ++ci) {
        const auto& ganim = asset.animations[ci];
        Clip out;
        out.name = InternName(
            arena, std::string_view(ganim.name.data(), ganim.name.size()));
        out.samplers = AllocSliceOrDie<AnimationSampler>(
            arena, static_cast<uint32_t>(ganim.samplers.size()), "clip sampler");
        uint32_t sampler_k = 0;
        for (const auto& gs : ganim.samplers) {
            AnimationSampler s;
            switch (gs.interpolation) {
                case fastgltf::AnimationInterpolation::Step:
                    s.interp = AnimationInterpolation::kStep;
                    break;
                case fastgltf::AnimationInterpolation::CubicSpline:
                    s.interp = AnimationInterpolation::kCubicSpline;
                    break;
                case fastgltf::AnimationInterpolation::Linear:
                default:
                    s.interp = AnimationInterpolation::kLinear;
                    break;
            }
            // #229 M1: store accessor handles only -- the keyframes are read
            // lazily for the selected walk clip below, so dozens of unused
            // clips cost zero keyframe allocations.
            s.input_accessor = static_cast<uint32_t>(gs.inputAccessor);
            s.output_accessor = static_cast<uint32_t>(gs.outputAccessor);
            const auto& vAcc = asset.accessors[gs.outputAccessor];
            s.value_kind = (vAcc.type == fastgltf::AccessorType::Vec4)     ? 1
                           : (vAcc.type == fastgltf::AccessorType::Scalar) ? 2
                                                                           : 0;
            out.samplers.data(arena)[sampler_k++] = s;
        }
        out.channels = AllocSliceOrDie<AnimationChannel>(
            arena, static_cast<uint32_t>(ganim.channels.size()), "clip channel");
        uint32_t channel_k = 0;
        for (const auto& gc : ganim.channels) {
            AnimationChannel ch;
            ch.samplerIndex = static_cast<int32_t>(gc.samplerIndex);
            ch.nodeIndex = gc.nodeIndex.has_value()
                               ? static_cast<int32_t>(*gc.nodeIndex)
                               : -1;
            switch (gc.path) {
                case fastgltf::AnimationPath::Translation:
                    ch.path = AnimationPath::kTranslation;
                    break;
                case fastgltf::AnimationPath::Rotation:
                    ch.path = AnimationPath::kRotation;
                    break;
                case fastgltf::AnimationPath::Scale:
                    ch.path = AnimationPath::kScale;
                    break;
                case fastgltf::AnimationPath::Weights:
                    ch.path = AnimationPath::kWeights;
                    break;
            }
            out.channels.data(arena)[channel_k++] = ch;
        }
        cold.clips.push_back(std::move(out));
    }

    if (!asset.scenes.empty()) {
        for (auto ni : asset.scenes[0].nodeIndices) hot.rootNodes.push_back(static_cast<int32_t>(ni));
    }

    cold.bind_pose.resize(cold.nodes.size());
    for (size_t i = 0; i < cold.nodes.size(); ++i) {
        const Node& nd = cold.nodes[i];
        AnimatedTRS trs;
        glm::vec3 skew;
        glm::vec4 persp;
        glm::decompose(nd.localTransform, trs.S, trs.R, trs.T, skew, persp);
        cold.bind_pose[i] = trs;
    }

    {
        const uint32_t n = static_cast<uint32_t>(cold.nodes.size());
        cold.gpu_parent.assign(n, -1);
        for (uint32_t i = 0; i < n; ++i) {
            const cairns::ArenaSlice<int32_t>& kids = cold.nodes[i].children;
            for (uint32_t ki = 0; ki < kids.size(); ++ki) {
                const int32_t c = kids.data(arena)[ki];
                if (c >= 0 && static_cast<uint32_t>(c) < n) {
                    cold.gpu_parent[static_cast<uint32_t>(c)] =
                        static_cast<int32_t>(i);
                }
            }
        }
        cold.gpu_topo.clear();
        cold.gpu_topo.reserve(n);
        std::vector<int32_t> stack;
        stack.reserve(n);
        for (auto it = hot.rootNodes.rbegin(); it != hot.rootNodes.rend(); ++it) {
            stack.push_back(*it);
        }
        while (!stack.empty()) {
            int32_t ni = stack.back();
            stack.pop_back();
            if (ni < 0 || static_cast<uint32_t>(ni) >= n) {
                continue;
            }
            cold.gpu_topo.push_back(ni);
            const Node& nd = cold.nodes[static_cast<uint32_t>(ni)];
            // reverse push to preserve child order on the stack.
            for (uint32_t ci = nd.children.size(); ci-- > 0;) {
                stack.push_back(nd.children.data(arena)[ci]);
            }
        }
        cold.gpu_bind_pose.resize(n);
        for (uint32_t i = 0; i < n; ++i) {
            const AnimatedTRS& s = cold.bind_pose[i];
            cold.gpu_bind_pose[i].T = glm::vec4(s.T, 0.0f);
            cold.gpu_bind_pose[i].R = glm::vec4(s.R.x, s.R.y, s.R.z, s.R.w);
            cold.gpu_bind_pose[i].S = glm::vec4(s.S, 0.0f);
        }
    }

    int32_t walk_clip = -1;
    {
        auto contains_ci = [](std::string_view s, const char* needle) {
            const size_t n = std::strlen(needle);
            if (s.size() < n) return false;
            for (size_t i = 0; i + n <= s.size(); ++i) {
                bool ok = true;
                for (size_t k = 0; k < n; ++k) {
                    char a = static_cast<char>(std::tolower(s[i + k]));
                    char b = static_cast<char>(std::tolower(needle[k]));
                    if (a != b) { ok = false; break; }
                }
                if (ok) return true;
            }
            return false;
        };
        int walk = -1;
        int run = -1;
        for (size_t i = 0; i < cold.clips.size(); ++i) {
            const std::string_view cn = ResolveName(arena, cold.clips[i].name);
            if (walk < 0 && contains_ci(cn, "walk")) {
                walk = static_cast<int>(i);
            } else if (run < 0 && contains_ci(cn, "run")) {
                run = static_cast<int>(i);
            }
        }
        walk_clip = (walk >= 0) ? walk : (run >= 0 ? run : 0);
    }
    if (!cold.clips.empty()) {
        const Clip& clip = cold.clips[static_cast<size_t>(walk_clip)];
        cold.gpu_samplers.reserve(clip.samplers.size());
        float clip_dur = 0.0f;
        for (uint32_t smp = 0; smp < clip.samplers.size(); ++smp) {
            const AnimationSampler& s = clip.samplers.data(arena)[smp];
            GpuSampler gs{};
            gs.times_off = static_cast<uint32_t>(cold.gpu_times.size());
            gs.values_off = static_cast<uint32_t>(cold.gpu_values.size());
            gs.interp = static_cast<uint32_t>(s.interp);
            // #229 M1: read keyframes straight from the glTF accessors into the
            // flat tables -- only the walk clip pays the read + the allocation.
            const auto& tAcc = asset.accessors[s.input_accessor];
            const size_t t_begin = cold.gpu_times.size();
            cold.gpu_times.reserve(t_begin + tAcc.count);
            fastgltf::iterateAccessor<float>(asset, tAcc,
                [&](float t) { cold.gpu_times.push_back(t); });
            gs.count = static_cast<uint32_t>(cold.gpu_times.size() - t_begin);
            if (cold.gpu_times.size() > t_begin &&
                cold.gpu_times.back() > clip_dur) {
                clip_dur = cold.gpu_times.back();
            }
            const auto& vAcc = asset.accessors[s.output_accessor];
            cold.gpu_values.reserve(cold.gpu_values.size() + vAcc.count);
            if (s.value_kind == 1) {  // Vec4 (rotation quat, .xyzw)
                fastgltf::iterateAccessor<glm::vec4>(asset, vAcc,
                    [&](glm::vec4 v) { cold.gpu_values.push_back(v); });
            } else if (s.value_kind == 2) {  // Scalar (weights -> .x)
                fastgltf::iterateAccessor<float>(asset, vAcc,
                    [&](float v) {
                        cold.gpu_values.push_back(glm::vec4(v, 0.0f, 0.0f, 0.0f));
                    });
            } else {  // Vec3 (T/S -> widen w=0)
                fastgltf::iterateAccessor<glm::vec3>(asset, vAcc,
                    [&](glm::vec3 v) {
                        cold.gpu_values.push_back(glm::vec4(v, 0.0f));
                    });
            }
            cold.gpu_samplers.push_back(gs);
        }
        cold.gpu_clip_duration = clip_dur;
        cold.gpu_channels.reserve(clip.channels.size());
        for (uint32_t chn = 0; chn < clip.channels.size(); ++chn) {
            const AnimationChannel& ch = clip.channels.data(arena)[chn];
            GpuChannel gc{};
            gc.node_idx = ch.nodeIndex;
            gc.path = static_cast<uint32_t>(ch.path);
            gc.sampler_idx = ch.samplerIndex;
            cold.gpu_channels.push_back(gc);
        }
    }

    if (!cold.skins.empty()) {
        const Skin& sk = cold.skins[0];
        cold.gpu_joint_nodes.assign(
            sk.jointNodes.data(arena),
            sk.jointNodes.data(arena) + sk.jointNodes.size());
        cold.gpu_inverse_binds.assign(
            sk.inverseBinds.data(arena),
            sk.inverseBinds.data(arena) + sk.inverseBinds.size());
        for (uint32_t i = 0; i < cold.nodes.size(); ++i) {
            if (cold.nodes[i].meshIndex >= 0 && cold.nodes[i].skinIndex == 0) {
                cold.gpu_mesh_node = static_cast<int32_t>(i);
                break;
            }
        }
    }

    return true;
}

// #220 Step 3: takes split-out Scene Hot+Cold; reads CPU temporaries
// from Cold and writes resolved handles into Hot.
inline void PreparePrefabResources(Prefab::Hot& hot, Prefab::Cold& cold,
                                   rhi::Resources& rm, rhi::Allocator& alloc,
                                   cairns::ResourceManager<Material>& materials) {
    // Textures
    for (const auto& texDescIn : cold.loaded_textures) {
        rhi::TextureDesc d;
        d.dimensions = {static_cast<int32_t>(texDescIn.width),
                        static_cast<int32_t>(texDescIn.height), 1};
        d.format = rhi::Format::kRgba8Unorm;
        d.mip_levels = static_cast<uint32_t>(texDescIn.levels > 0 ? texDescIn.levels : 1);
        d.array_layers = 1;
        d.usage = rhi::kTexUsageSampled | rhi::kTexUsageTransferDst;
        d.memory = rhi::Memory::kDefault;
        d.initial_data = std::span<const uint8_t>(
            static_cast<const uint8_t*>(texDescIn.src_image),
            static_cast<size_t>(texDescIn.src_bytes_per_row) *
                static_cast<size_t>(texDescIn.height));
        cold.textureHandles.push_back(rm.CreateTexture(alloc, d));
    }
    
    // Samplers
    for (const auto& info : cold.loaded_samplers) {
        auto map_filter = [](rhi::SamplerFilter f) {
            return f == rhi::SamplerFilter::Nearest ? rhi::Filter::kNearest : rhi::Filter::kLinear;
        };
        auto map_mip = [](rhi::SamplerMipFilter f) {
            return f == rhi::SamplerMipFilter::Linear ? rhi::Filter::kLinear : rhi::Filter::kNearest;
        };
        auto map_addr = [](rhi::SamplerAddressMode m) {
            switch (m) {
                case rhi::SamplerAddressMode::MirroredRepeat: return rhi::AddressMode::kMirroredRepeat;
                case rhi::SamplerAddressMode::ClampToEdge:    return rhi::AddressMode::kClampToEdge;
                case rhi::SamplerAddressMode::ClampToBorder:  return rhi::AddressMode::kClampToBorder;
                default:                                      return rhi::AddressMode::kRepeat;
            }
        };
        rhi::SamplerDesc d;
        d.min_filter = map_filter(info.minFilter);
        d.mag_filter = map_filter(info.magFilter);
        d.mip_filter = map_mip(info.mipFilter);
        d.address_mode = map_addr(info.addressModeU);
        d.max_anisotropy = 8.0f;
        d.max_lod = 1000.0f;
        cold.samplerHandles.push_back(rm.CreateSampler(d));
    }
    
    // ONLY DOES UNLIT MATERIALS
    assert(cold.materialToTextureIndex.size() == cold.materialToSamplerIndex.size());
    for ( size_t i = 0; i < cold.materialToTextureIndex.size(); ++i ) {
        uint32_t gltf_tex_idx = cold.materialToTextureIndex[i];
        uint32_t gltf_sampler_idx = cold.materialToSamplerIndex[i];
        auto t = cold.textureHandles[gltf_tex_idx];
        auto s = cold.samplerHandles[gltf_sampler_idx];
        // #220 Step 1: acquire pool slot, populate Cold. Hot.set2 (the
        // bind group) is filled in later by Engine::initRenderPipeline
        // since it needs rhi_.frames/resources to build the descriptor.
        const cairns::Handle<Material> mat_id = materials.Acquire();
        Material::Cold* cold = materials.GetCold(mat_id);
        cold->color = t;
        cold->sampler = s;
        hot.materials.push_back(mat_id);  // #220 Step 3: was materialIds
    }
}

} // namespace cairns
