glslc unlit.vert -o unlit.vert.spv
glslc unlit.frag -o unlit.frag.spv
glslc imgui.vert -o imgui.vert.spv
glslc imgui.frag -o imgui.frag.spv
glslc composite_pip.vert -o composite_pip.vert.spv
glslc composite_pip.frag -o composite_pip.frag.spv
glslc depthviz.frag -o depthviz.frag.spv
glslc lit.vert -o lit.vert.spv
glslc lit.frag -o lit.frag.spv
glslc lit_noid.frag -o lit_noid.frag.spv
