#!/usr/bin/env python3
"""Amalgamate cairns-gfx's own C++ sources into one topo-sorted unity-build TU.

Walks src/ for .hpp/.cpp, resolves project `#include "..."` into a dependency
graph, topo-sorts it (a header is emitted before anything that includes it; the
.cpp files land after the headers they need), and concatenates everything into a
single translation unit.

third_party/ is NEVER inlined: external `#include <...>` lines (and any project
"..." include that doesn't resolve under src/, e.g. the cmake-generated
util/gfx_config.hpp) are passed through verbatim and resolved at compile time via
the normal -I paths. We deliberately do NOT hoist/reorder those, so
define-before-include patterns (e.g. STB_IMAGE_IMPLEMENTATION) stay intact.

Usage:
    python3 scripts/amalgamate.py            # -> tmp/amalgamation.cpp (gitignored)
    python3 scripts/amalgamate.py out.cpp    # -> given path
"""
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_ROOT = os.path.join(REPO_ROOT, "src")
ASSETS_ROOT = os.path.join(REPO_ROOT, "assets")
EXTS = {".hpp", ".h", ".cpp", ".cc", ".mm", ".c"}
SHADER_EXTS = {".glsl", ".comp", ".vert", ".frag", ".tesc", ".tese", ".geom", ".metal"}

INC_QUOTE = re.compile(r'^\s*#\s*include\s*"([^"]+)"')
INC_ANGLE = re.compile(r'^\s*#\s*include\s*<')
PRAGMA_ONCE = re.compile(r'^\s*#\s*pragma\s+once\s*$')


def collect():
    files = []
    for dirpath, _dirnames, filenames in os.walk(SRC_ROOT):
        for fn in filenames:
            if os.path.splitext(fn)[1] in EXTS:
                files.append(os.path.join(dirpath, fn))
    return files


def resolve(inc, from_dir):
    for base in (from_dir, SRC_ROOT):
        cand = os.path.normpath(os.path.join(base, inc))
        if os.path.isfile(cand):
            return cand
    return None  # unresolved -> external / generated, pass through verbatim


def main():
    files = collect()
    fileset = set(files)
    deps = {f: [] for f in files}
    for f in files:
        from_dir = os.path.dirname(f)
        with open(f, errors="replace") as fh:
            for line in fh:
                m = INC_QUOTE.match(line)
                if not m:
                    continue
                target = resolve(m.group(1), from_dir)
                if target in fileset:
                    deps[f].append(target)

    # Topo sort: headers first (so dependents see them), then .cpp. DFS post-order
    # over the include DAG; cycles (mutual #pragma once headers) are broken arbitrarily.
    order = []
    state = {}  # 1 = done, 0 = on stack

    def visit(f):
        s = state.get(f)
        if s is not None:
            return
        state[f] = 0
        for dep in deps[f]:
            visit(dep)
        state[f] = 1
        order.append(f)

    is_header = lambda f: os.path.splitext(f)[1] in (".hpp", ".h")
    for f in sorted(filter(is_header, files)):
        visit(f)
    for f in sorted(f for f in files if not is_header(f)):
        visit(f)

    out_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(REPO_ROOT, "tmp", "amalgamation.cpp")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    out = open(out_path, "w")
    out.write("// cairns-gfx amalgamated unity TU -- generated by scripts/amalgamate.py\n")
    out.write("// topo-sorted over src/ include graph; third_party/ left as external includes.\n")
    for f in order:
        rel = os.path.relpath(f, REPO_ROOT)
        out.write("\n// ==================== {} ====================\n".format(rel))
        with open(f, errors="replace") as fh:
            for line in fh:
                if PRAGMA_ONCE.match(line):
                    continue
                m = INC_QUOTE.match(line)
                if m and resolve(m.group(1), os.path.dirname(f)) in fileset:
                    continue  # this header is inlined elsewhere in the TU
                out.write(line)  # keep external <...>, generated/unresolved "...", and code

    shader_files = []
    if os.path.isdir(ASSETS_ROOT):
        for fn in sorted(os.listdir(ASSETS_ROOT)):
            ext = os.path.splitext(fn)[1].lower()
            if ext in SHADER_EXTS:
                shader_files.append(os.path.join(ASSETS_ROOT, fn))
    if shader_files:
        out.write("\n// ==================== SHADERS ====================\n")
        for sf in shader_files:
            rel = os.path.relpath(sf, REPO_ROOT)
            out.write("\n// -------------------- {} --------------------\n".format(rel))
            out.write("#if 0  // shader source, not compiled as C++\n")
            with open(sf, errors="replace") as fh:
                out.write(fh.read())
            if not out.tell() or True:
                out.write("\n#endif\n")
    out.close()
    sys.stderr.write("amalgamated {} files + {} shaders -> {}\n".format(
        len(order), len(shader_files), out_path))


if __name__ == "__main__":
    main()
